In [1]:
import numpy as np 
print("Numpy imported successfully")

Numpy imported successfully


In [7]:
# creating nd arrays
arr_list = np.array([1,2,3,4,5,6,])= np.a
arr_range = np.arange(6)
arr_zeros = np.zeros(3)
arr_ones = np.ones(3)
arr_twos = np.full(4,2)
print(arr_list)
print(arr_range)
print(arr_zeros)
print(arr_ones)
print(arr_twos)

[1 2 3 4 5 6]
[0 1 2 3 4 5]
[0. 0. 0.]
[1. 1. 1.]
[2 2 2 2]


In [14]:
# Array shapes -> They show the number of elements in each dimension 
arr_list = np.array([1,2,3,4,5,6])
print(arr_list.shape)
arr_2d = np.array([[1,2,3,],[4,5,6]])
print(arr_2d.shape)

(6,)
(2, 3)


In [17]:
# Reshaping arrays -> The total number of elements remains the same 
# Convert a 1D array into a 2x3 matrix
arr = np.array([[2,3],[3,5],[4,6]])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

# Flatten any array back to 1D using -1
flattened_arr = reshaped_arr.reshape(-1)
print(flattened_arr)  # Output: [1 2 3 4 5 6]


[[2 3 3]
 [5 4 6]]
[2 3 3 5 4 6]


In [21]:
#  BAsic indexing in the context of the numpy moreso in terms of the position
a = np.array([1,2,3,4,5,6])
f1 = a[0] 
#  f1 is assigned the first element of the array list 
# testing the two dimensions array 
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
# target the second row and third column element bearing in mind that we start counting from zero

f2 =b[1,2]
print(f2)


6


In [2]:
# I will be exploring slicing in this context 
a = np.arange(10)
reversed_array = a[::-1]
# slicing works with the principle of [start,stop,step]
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


In [9]:
#  consider the array that is defined 
a=np.array([1,2,3,4,5])
selected_array = a[1:5]
print(selected_array)
# testing the array with two steps
b = np.arange(10)
steps_2_array = b[::2]
print(steps_2_array)

[2 3 4 5]
[0 2 4 6 8]


In [11]:
# Boolean indixing -> It is also referred to as masking
a = np.array([1,-2,3,-4,5])
mask = a>0
print(a[mask])
#  The code is similar to the same 
print(a[a>0])


[1 3 5]
[1 3 5]


In [26]:
b = np.arange(10)
print(b[~(b>5)])

    


[0 1 2 3 4 5]


In [28]:
# Boolean indexing always returns a copy not a value and it is flatted
c = np.array([[1,2,3],[4,5,6]])
print(c[c>4])

[5 6]


In [32]:
# Fancy Indexing (integer array indexing)
a = np.array([10,20,30,40,50])
idx =[0,2,4]
print(a[idx])
# Repeats allowed 
print(a[[3,3,1]])
# listing the last elements
print(a[-1])

[10 30 50]
[40 40 20]
50


In [36]:
# combining both indexing and reshape 
a = np.arange(1,13).reshape(3,4)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
c = np.arange(1, 13).reshape(3, 4)
print(c[0:2, [0, 2]])       # slice rows, fancy-index columns
print(c[c[:, 0] > 4, :] )     # boolean-select rows based on column 0's values

[[1 3]
 [5 7]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
arr = np.arange(1,26).reshape(5,5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
# Getting the element 13 using basic indexing
print(arr[3:3])

[]


In [5]:
#  vectorized operations 
#  exampe on the simple arithmetics 
arr1= np.array([1,2,3,4])
arr2 = np.array([5,6,6,7])
print(arr1 + arr2)
# logical comparison 
arr = np.array([5,12,18,3])
mask = arr>10
print(mask)
print(arr[mask])


[ 6  8  9 11]
[False  True  True False]
[12 18]


In [6]:
#mathematical functions 
arr = np.array([0,np.pi/2,np.pi])
print(np.sin(arr))
print(np.exp(arr))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]


In [8]:
# linear algebra and matrix multiplication 
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])
results = matrix_a@matrix_b
print(results)


[[19 22]
 [43 50]]


In [9]:
# Broadasting. When arrays do not have identical shapes numpy broadcasting engine virtually expands or stretches the smaller array across messing dimensions without copying data in memory 
matrix_a = np.array([[1,2,3],[4,5,6]])
row_vector = np.array([1,0,1])
print(matrix_a + row_vector)


[[2 2 4]
 [5 5 7]]


In [11]:
# customized vectorized function 
def my_custom_function(x):
    return x**2 if x>0 else 0
vectorized_fun = np.vectorize(my_custom_function)
arr = np.array([-1,2,-3,4])
print(vectorized_fun(arr))

[ 0  4  0 16]
